In [18]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
from datetime import datetime
from sklearn import preprocessing
from sklearn.cluster import *
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\benxi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

# Read Data

In [19]:
df = pd.read_csv('../final_data.csv',sep='|')
df


link  \
0     https://www.cnn.com/2023/11/20/middleeast/gaza...   
1     https://www.cnn.com/2023/11/20/us/5-things-to-...   
2     https://www.cnn.com/2023/11/20/china/china-ara...   
3     https://www.cnn.com/2023/11/20/world/gaza-al-s...   
4     https://www.cnn.com/middleeast/live-news/israe...   
...                                                 ...   
1773  https://www.scmp.com/news/world/united-states-...   
1774  https://www.scmp.com/news/hong-kong/politics/a...   
1775  https://www.scmp.com/news/china/diplomacy/arti...   
1776  https://www.scmp.com/comment/opinion/article/3...   
1777  https://www.scmp.com/news/world/middle-east/ar...   

                                                  title          author  \
0     One evacuated from northern Gaza, the other di...             cnn   
1     5 things to know for Nov. 20: Israel, Campaign...             cnn   
2     China calls for ‘urgent’ action on Gaza as Mus...             cnn   
3     Premature, sick babies arrive in Egypt from Ga...             cnn   
4     Israel-Hamas war rages as humanitarian crisis ...             cnn   
...                                                 ...             ...   
1773  Israel-Gaza war: Donald Trump slammed for call...         Reuters   
1774  Hong Kong Muslim groups register protest with ...     Lo Hoi-ying   
1775  Israel-Hamas war: mother of kidnapped woman sa...   Sylvie Zhuang   
1776  Israel-Hamas war shows limits of forecasting i...  Nicholas Spiro   
1777  Israel-Gaza war: Blinken tells Netanyahu US ‘b...         Reuters   

                          date  \
0     2023-11-20T15:53:09.370Z   
1     2023-11-20T15:53:25.553Z   
2     2023-11-20T10:17:50.296Z   
3     2023-11-20T15:52:51.889Z   
4     2023-11-20T15:56:38.659Z   
...                        ...   
1773  2023-10-12T18:06:01.000Z   
1774  2023-10-12T14:20:33.000Z   
1775  2023-10-12T12:46:56.000Z   
1776  2023-10-12T12:30:11.000Z   
1777  2023-10-12T11:38:56.000Z   

                                                content  
0     When Rami Mahmoud left his family’s home to bu...  
1     CNN’s 5 Things brings you the news you need to...  
2     The world must “must act urgently” to stem the...  
3     Ambulances carrying premature, sick babies cro...  
4     Israel is releasing videos that it says prove ...  
...                                                 ...  
1773  Israel and the White House on Thursday condemn...  
1774  Muslim groups in Hong Kong have registered a s...  
1775  The mother of Noa Argamani, a woman believed t...  
1776  Boxer Mike Tyson’s famous quote – “Everyone ha...  
1777  US Secretary of State Antony Blinken on Thursd...  

[1778 rows x 5 columns]

In [20]:
contents= df['content'].copy().astype(str)
dates = df['date'].copy()

# contents.head(3)
# contentList=[]
# for text in contents:
#     tokens = word_tokenize(text)
#     for index,token in enumerate(tokens):
#         tokens[index]=token.lower()
#     contentList.append(tokens)
    

# print(contentList[0])

# normalize data

def parse_date(date_string):
    try:
        return datetime.strptime(date_string, '%Y-%m-%dT%H:%M:%S.%fZ')
    except Exception as e:
        print (e)
        print("now try '%Y-%m-%dT%H:%M:%S:%fZ'")
        return datetime.strptime(date_string, '%Y-%m-%dT%H:%M:%SZ')

for index,timeString in enumerate(dates):
    timeStr =parse_date(timeString)
    formatted_time = timeStr.strftime('%Y%m%d%H')
    dates[index]=int(formatted_time)
print(dates[0:3])

normalied_dates=(dates-dates.min())/(dates.max()-dates.min())
normalied_dates:np.ndarray = normalied_dates.values.reshape(-1,1) #convert to numpy array
print(normalied_dates[0:3])


time data '2023-11-15T02:59:11Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
now try '%Y-%m-%dT%H:%M:%S:%fZ'
time data '2023-11-20T01:21:27Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
now try '%Y-%m-%dT%H:%M:%S:%fZ'
time data '2023-11-02T20:12:14Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
now try '%Y-%m-%dT%H:%M:%S:%fZ'
time data '2023-10-31T04:23:30Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
now try '%Y-%m-%dT%H:%M:%S:%fZ'
time data '2023-10-30T12:51:13Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
now try '%Y-%m-%dT%H:%M:%S:%fZ'
time data '2023-10-27T22:59:06Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
now try '%Y-%m-%dT%H:%M:%S:%fZ'
time data '2023-10-26T16:32:51Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
now try '%Y-%m-%dT%H:%M:%S:%fZ'
time data '2023-10-26T04:38:00Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
now try '%Y-%m-%dT%H:%M:%S:%fZ'
time data '2023-10-26T01:14:50Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
now try '%Y-%m-%dT%H:%M:%S:%fZ'
t

In [22]:
print(contents)

0       When Rami Mahmoud left his family’s home to bu...
1       CNN’s 5 Things brings you the news you need to...
2       The world must “must act urgently” to stem the...
3       Ambulances carrying premature, sick babies cro...
4       Israel is releasing videos that it says prove ...
                              ...                        
1773    Israel and the White House on Thursday condemn...
1774    Muslim groups in Hong Kong have registered a s...
1775    The mother of Noa Argamani, a woman believed t...
1776    Boxer Mike Tyson’s famous quote – “Everyone ha...
1777    US Secretary of State Antony Blinken on Thursd...
Name: content, Length: 1778, dtype: object


In [27]:
tf_idf=TfidfVectorizer(stop_words=stopwords.words('english'),lowercase=True) # other possible method doc2vec
x_tf_idf = tf_idf.fit_transform(contents)
x_tf_idf=x_tf_idf.todense()
print(x_tf_idf.shape)
print(x_tf_idf[:3])
#normalize the vector
from sklearn.preprocessing import normalize
x_tf_idf=normalize(np.asarray(x_tf_idf), axis=0, norm='max')
print(x_tf_idf.shape)
print(x_tf_idf[:3])

(1778, 8637)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(1778, 8637)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [28]:
# merge the feature
X_train = np.hstack((x_tf_idf,normalied_dates))
print(X_train.shape)

(1778, 8638)


In [35]:
# clustering
clustering = MeanShift(bandwidth=1.512,bin_seeding=True,n_jobs=-1).fit(np.asarray(X_train)) # other possbile clustering dbscan, bayes gaussian mixture
print(len(clustering.cluster_centers_))

12


In [36]:
#label text
group=clustering.predict(np.asarray(X_train))
print(group.shape)
df['group']=group
df

(1778,)


link  \
0     https://www.cnn.com/2023/11/20/middleeast/gaza...   
1     https://www.cnn.com/2023/11/20/us/5-things-to-...   
2     https://www.cnn.com/2023/11/20/china/china-ara...   
3     https://www.cnn.com/2023/11/20/world/gaza-al-s...   
4     https://www.cnn.com/middleeast/live-news/israe...   
...                                                 ...   
1773  https://www.scmp.com/news/world/united-states-...   
1774  https://www.scmp.com/news/hong-kong/politics/a...   
1775  https://www.scmp.com/news/china/diplomacy/arti...   
1776  https://www.scmp.com/comment/opinion/article/3...   
1777  https://www.scmp.com/news/world/middle-east/ar...   

                                                  title          author  \
0     One evacuated from northern Gaza, the other di...             cnn   
1     5 things to know for Nov. 20: Israel, Campaign...             cnn   
2     China calls for ‘urgent’ action on Gaza as Mus...             cnn   
3     Premature, sick babies arrive in Egypt from Ga...             cnn   
4     Israel-Hamas war rages as humanitarian crisis ...             cnn   
...                                                 ...             ...   
1773  Israel-Gaza war: Donald Trump slammed for call...         Reuters   
1774  Hong Kong Muslim groups register protest with ...     Lo Hoi-ying   
1775  Israel-Hamas war: mother of kidnapped woman sa...   Sylvie Zhuang   
1776  Israel-Hamas war shows limits of forecasting i...  Nicholas Spiro   
1777  Israel-Gaza war: Blinken tells Netanyahu US ‘b...         Reuters   

                          date  \
0     2023-11-20T15:53:09.370Z   
1     2023-11-20T15:53:25.553Z   
2     2023-11-20T10:17:50.296Z   
3     2023-11-20T15:52:51.889Z   
4     2023-11-20T15:56:38.659Z   
...                        ...   
1773  2023-10-12T18:06:01.000Z   
1774  2023-10-12T14:20:33.000Z   
1775  2023-10-12T12:46:56.000Z   
1776  2023-10-12T12:30:11.000Z   
1777  2023-10-12T11:38:56.000Z   

                                                content  group  
0     When Rami Mahmoud left his family’s home to bu...      0  
1     CNN’s 5 Things brings you the news you need to...      0  
2     The world must “must act urgently” to stem the...      0  
3     Ambulances carrying premature, sick babies cro...      0  
4     Israel is releasing videos that it says prove ...      0  
...                                                 ...    ...  
1773  Israel and the White House on Thursday condemn...      0  
1774  Muslim groups in Hong Kong have registered a s...      0  
1775  The mother of Noa Argamani, a woman believed t...      0  
1776  Boxer Mike Tyson’s famous quote – “Everyone ha...      0  
1777  US Secretary of State Antony Blinken on Thursd...      0  

[1778 rows x 6 columns]

In [37]:
#pick earliest news
groupDates=np.hstack((dates.values.reshape(-1,1),group.reshape(-1,1)))
groupDates=pd.DataFrame(groupDates,columns=["date","group"])
groupDates=groupDates.astype({"date":'Int64',"group":'int'})
result = groupDates.groupby('group')['date'].idxmin()
print(groupDates)
print(result)


            date  group
0     2023112015      0
1     2023112015      0
2     2023112010      0
3     2023112015      0
4     2023112015      0
...          ...    ...
1773  2023101218      0
1774  2023101214      0
1775  2023101212      0
1776  2023101212      0
1777  2023101211      0

[1778 rows x 2 columns]
group
0     1187
1      549
2      965
3      410
4     1502
5     1023
6     1358
7     1349
8     1471
9      424
10    1222
11    1159
Name: date, dtype: int64


In [38]:
# selected article
df.loc[result.values]

link  \
1187  https://www.cnn.com/2020/01/29/politics/pro-is...   
549   https://www.cnn.com/2023/09/08/middleeast/isra...   
965   https://www.cnn.com/2021/06/02/sport/gaza-wome...   
410   https://www.cnn.com/2023/10/14/middleeast/hama...   
1502  https://abcnews.go.com/International/wireStory...   
1023  https://www.cnn.com/2021/05/13/world/meanwhile...   
1358  https://abcnews.go.com/US/wireStory/palestinia...   
1349  https://abcnews.go.com/US/wireStory/israel-ham...   
1471  https://abcnews.go.com/International/wireStory...   
424   https://www.cnn.com/2023/10/13/media/israel-ha...   
1222  https://abcnews.go.com/US/wireStory/israelis-a...   
1159  https://www.cnn.com/2020/04/28/middleeast/leba...   

                                                  title  \
1187  Pro-Israel Democratic super PAC takes aim at B...   
549   Israel’s Arab citizens demand justice after al...   
965   How boxing is changing the way society looks a...   
410   Who is El Deif, alleged mastermind of the Hama...   
1502  A contest erupts in Uganda over the tainted le...   
1023  The explosion of Israeli-Palestinian violence ...   
1358  Palestinians plead 'stop the bombs' at UN meet...   
1349  The Israel-Hamas war could threaten already fr...   
1471  Fights in bread lines, despair in shelters: Wa...   
424   Explosive claims about the Israel-Hamas war ar...   
1222  Israelis abroad desperately try to head home t...   
1159  75% of Lebanon needs aid after coronavirus, an...   

                                                 author  \
1187                                                cnn   
549                                                 cnn   
965                                                 cnn   
410                                                 cnn   
1502                   RODNEY MUHUMUZA Associated Press   
1023                                                cnn   
1358                  EDITH M. LEDERER Associated Press   
1349   FATIMA HUSSEIN Associated Press and JOSH BOAK...   
1471                      ISABEL DEBRE Associated Press   
424                                                 cnn   
1222   JOCELYN NOVECK Associated Press, MENELAOS HAD...   
1159                                                cnn   

                          date  \
1187      2020-01-29T17:54:30Z   
549       2023-09-08T10:04:56Z   
965       2021-06-02T09:17:40Z   
410       2023-10-14T11:11:50Z   
1502  2023-11-13T01:19:00.000Z   
1023      2021-05-13T14:22:47Z   
1358  2023-10-26T18:51:00.000Z   
1349  2023-10-26T00:15:00.000Z   
1471  2023-11-09T12:18:00.000Z   
424       2023-10-13T13:04:10Z   
1222  2023-10-11T00:13:00.000Z   
1159      2020-04-29T15:24:19Z   

                                                content  group  
1187  A pro-Israel Democratic super PAC is launching...      0  
549      Sajida Abu Salah, clad in all black, is angry.      1  
965   “I don’t like violence,” says Reema Aburahma, ...      2  
410   It is with a weird retrospective guilt that I ...      3  
1502             Can Idi Amin possibly be rehabilitated      4  
1023  “Just when I thought I was out, they pull me b...      5  
1358                   “Stop the bombs and save lives!”      6  
1349  Economic crises are rippling through the count...      7  
1471                Fistfights break out in bread lines      8  
424          The public is enveloped in the fog of war.      9  
1222  Some Israelis living overseas aren’t running f...     10  
1159  Cash-strapped Lebanon is facing growing turmoi...     11