In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
from datetime import datetime
from sklearn import preprocessing
from sklearn.cluster import *
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\benxi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

# Read Data

In [2]:
df = pd.read_csv('../final_data.csv',sep='|')
df


link  \
0     https://www.cnn.com/middleeast/live-news/israe...   
1     https://www.cnn.com/2023/11/20/world/mosab-abu...   
2     https://www.cnn.com/2023/11/21/middleeast/isra...   
3     https://www.cnn.com/2023/11/21/world/gaza-host...   
4     https://www.cnn.com/2023/11/20/politics/pollin...   
...                                                 ...   
1124  https://www.scmp.com/news/world/united-states-...   
1125  https://www.scmp.com/news/hong-kong/politics/a...   
1126  https://www.scmp.com/news/china/diplomacy/arti...   
1127  https://www.scmp.com/comment/opinion/article/3...   
1128  https://www.scmp.com/news/world/middle-east/ar...   

                                                  title          author  \
0     Israel-Hamas war rages as humanitarian crisis ...             cnn   
1     PEN International ‘deeply concerned’ by Palest...             cnn   
2     ‘Hope is hard to come by’: In the Red Sea reso...             cnn   
3     Frustrations spill over in Israel as hostage f...             cnn   
4     Polling shows a huge age gap divides the Democ...             cnn   
...                                                 ...             ...   
1124  Israel-Gaza war: Donald Trump slammed for call...         Reuters   
1125  Hong Kong Muslim groups register protest with ...     Lo Hoi-ying   
1126  Israel-Hamas war: mother of kidnapped woman sa...   Sylvie Zhuang   
1127  Israel-Hamas war shows limits of forecasting i...  Nicholas Spiro   
1128  Israel-Gaza war: Blinken tells Netanyahu US ‘b...         Reuters   

                          date  \
0     2023-11-21T15:17:02.846Z   
1     2023-11-21T12:54:13.029Z   
2     2023-11-21T06:23:14.252Z   
3     2023-11-21T04:51:30.424Z   
4     2023-11-20T23:41:49.107Z   
...                        ...   
1124  2023-10-12T18:06:01.000Z   
1125  2023-10-12T14:20:33.000Z   
1126  2023-10-12T12:46:56.000Z   
1127  2023-10-12T12:30:11.000Z   
1128  2023-10-12T11:38:56.000Z   

                                                content  
0     A deal to release some hostages in exchange fo...  
1     A Palestinian writer and poet who had been con...  
2     As the red alert alarm sounded in the busy hot...  
3     Tensions are boiling over in Israel as frustra...  
4     President Joe Biden has a problem with the Dem...  
...                                                 ...  
1124  Israel and the White House on Thursday condemn...  
1125  Muslim groups in Hong Kong have registered a s...  
1126  The mother of Noa Argamani, a woman believed t...  
1127  Boxer Mike Tyson’s famous quote – “Everyone ha...  
1128  US Secretary of State Antony Blinken on Thursd...  

[1129 rows x 5 columns]

In [3]:
contents= df['content'].copy().astype(str)
dates = df['date'].copy()

# contents.head(3)
# contentList=[]
# for text in contents:
#     tokens = word_tokenize(text)
#     for index,token in enumerate(tokens):
#         tokens[index]=token.lower()
#     contentList.append(tokens)
    

# print(contentList[0])

# normalize data

def parse_date(date_string):
    try:
        return datetime.strptime(date_string, '%Y-%m-%dT%H:%M:%S.%fZ')
    except Exception as e:
        print (e)
        print("now try '%Y-%m-%dT%H:%M:%S:%fZ'")
        return datetime.strptime(date_string, '%Y-%m-%dT%H:%M:%SZ')

for index,timeString in enumerate(dates):
    timeStr =parse_date(timeString)
    formatted_time = timeStr.strftime('%Y%m%d%H')
    dates[index]=int(formatted_time)
print(dates[0:3])

normalied_dates=(dates-dates.min())/(dates.max()-dates.min())
normalied_dates:np.ndarray = normalied_dates.values.reshape(-1,1) #convert to numpy array
print(normalied_dates[0:3])


time data '2023-11-15T02:59:11Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
now try '%Y-%m-%dT%H:%M:%S:%fZ'
time data '2023-11-21T15:01:29Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
now try '%Y-%m-%dT%H:%M:%S:%fZ'
time data '2023-11-02T20:12:14Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
now try '%Y-%m-%dT%H:%M:%S:%fZ'
time data '2023-10-31T04:23:30Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
now try '%Y-%m-%dT%H:%M:%S:%fZ'
time data '2023-10-30T12:51:13Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
now try '%Y-%m-%dT%H:%M:%S:%fZ'
time data '2023-10-27T22:59:06Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
now try '%Y-%m-%dT%H:%M:%S:%fZ'
time data '2023-10-26T16:32:51Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
now try '%Y-%m-%dT%H:%M:%S:%fZ'
time data '2023-10-26T04:38:00Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
now try '%Y-%m-%dT%H:%M:%S:%fZ'
time data '2023-10-26T01:14:50Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
now try '%Y-%m-%dT%H:%M:%S:%fZ'
t

In [4]:
print(contents)

0       A deal to release some hostages in exchange fo...
1       A Palestinian writer and poet who had been con...
2       As the red alert alarm sounded in the busy hot...
3       Tensions are boiling over in Israel as frustra...
4       President Joe Biden has a problem with the Dem...
                              ...                        
1124    Israel and the White House on Thursday condemn...
1125    Muslim groups in Hong Kong have registered a s...
1126    The mother of Noa Argamani, a woman believed t...
1127    Boxer Mike Tyson’s famous quote – “Everyone ha...
1128    US Secretary of State Antony Blinken on Thursd...
Name: content, Length: 1129, dtype: object


In [5]:
tf_idf=TfidfVectorizer(stop_words=stopwords.words('english'),lowercase=True) # other possible method doc2vec
x_tf_idf = tf_idf.fit_transform(contents)
x_tf_idf=x_tf_idf.todense()
print(x_tf_idf.shape)
print(x_tf_idf[:3])
#normalize the vector
from sklearn.preprocessing import normalize
x_tf_idf=normalize(np.asarray(x_tf_idf), axis=0, norm='max')
print(x_tf_idf.shape)
print(x_tf_idf[:3])

(1129, 7331)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(1129, 7331)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [6]:
# merge the feature
X_train = np.hstack((x_tf_idf,normalied_dates))
print(X_train.shape)

(1129, 7332)


In [7]:
# clustering
clustering = MeanShift(bandwidth=1.512,bin_seeding=True,n_jobs=-1).fit(np.asarray(X_train)) # other possbile clustering dbscan, bayes gaussian mixture
print(len(clustering.cluster_centers_))

12


In [8]:
#label text
group=clustering.predict(np.asarray(X_train))
print(group.shape)
df['group']=group
df

(1129,)


link  \
0     https://www.cnn.com/middleeast/live-news/israe...   
1     https://www.cnn.com/2023/11/20/world/mosab-abu...   
2     https://www.cnn.com/2023/11/21/middleeast/isra...   
3     https://www.cnn.com/2023/11/21/world/gaza-host...   
4     https://www.cnn.com/2023/11/20/politics/pollin...   
...                                                 ...   
1124  https://www.scmp.com/news/world/united-states-...   
1125  https://www.scmp.com/news/hong-kong/politics/a...   
1126  https://www.scmp.com/news/china/diplomacy/arti...   
1127  https://www.scmp.com/comment/opinion/article/3...   
1128  https://www.scmp.com/news/world/middle-east/ar...   

                                                  title          author  \
0     Israel-Hamas war rages as humanitarian crisis ...             cnn   
1     PEN International ‘deeply concerned’ by Palest...             cnn   
2     ‘Hope is hard to come by’: In the Red Sea reso...             cnn   
3     Frustrations spill over in Israel as hostage f...             cnn   
4     Polling shows a huge age gap divides the Democ...             cnn   
...                                                 ...             ...   
1124  Israel-Gaza war: Donald Trump slammed for call...         Reuters   
1125  Hong Kong Muslim groups register protest with ...     Lo Hoi-ying   
1126  Israel-Hamas war: mother of kidnapped woman sa...   Sylvie Zhuang   
1127  Israel-Hamas war shows limits of forecasting i...  Nicholas Spiro   
1128  Israel-Gaza war: Blinken tells Netanyahu US ‘b...         Reuters   

                          date  \
0     2023-11-21T15:17:02.846Z   
1     2023-11-21T12:54:13.029Z   
2     2023-11-21T06:23:14.252Z   
3     2023-11-21T04:51:30.424Z   
4     2023-11-20T23:41:49.107Z   
...                        ...   
1124  2023-10-12T18:06:01.000Z   
1125  2023-10-12T14:20:33.000Z   
1126  2023-10-12T12:46:56.000Z   
1127  2023-10-12T12:30:11.000Z   
1128  2023-10-12T11:38:56.000Z   

                                                content  group  
0     A deal to release some hostages in exchange fo...     11  
1     A Palestinian writer and poet who had been con...     11  
2     As the red alert alarm sounded in the busy hot...     11  
3     Tensions are boiling over in Israel as frustra...     11  
4     President Joe Biden has a problem with the Dem...     11  
...                                                 ...    ...  
1124  Israel and the White House on Thursday condemn...     11  
1125  Muslim groups in Hong Kong have registered a s...     11  
1126  The mother of Noa Argamani, a woman believed t...     11  
1127  Boxer Mike Tyson’s famous quote – “Everyone ha...     11  
1128  US Secretary of State Antony Blinken on Thursd...     11  

[1129 rows x 6 columns]

In [9]:
#pick earliest news
groupDates=np.hstack((dates.values.reshape(-1,1),group.reshape(-1,1)))
groupDates=pd.DataFrame(groupDates,columns=["date","group"])
groupDates=groupDates.astype({"date":'Int64',"group":'int'})
result = groupDates.groupby('group')['date'].idxmin()
print(groupDates)
print(result)


            date  group
0     2023112115     11
1     2023112112     11
2     2023112106     11
3     2023112104     11
4     2023112023     11
...          ...    ...
1124  2023101218     11
1125  2023101214     11
1126  2023101212     11
1127  2023101212     11
1128  2023101211     11

[1129 rows x 2 columns]
group
0     461
1     561
2     416
3     743
4     853
5     435
6     709
7     700
8     822
9     431
10    573
11    538
Name: date, dtype: int64


In [10]:
# selected article
df.loc[result.values]

link  \
461  https://www.cnn.com/2023/10/12/us/5-things-to-...   
561  https://abcnews.go.com/International/wireStory...   
416  https://www.cnn.com/2023/10/14/middleeast/hama...   
743  https://abcnews.go.com/International/wireStory...   
853  https://abcnews.go.com/International/wireStory...   
435  https://www.cnn.com/2023/10/13/investing/prema...   
709  https://abcnews.go.com/US/wireStory/palestinia...   
700  https://abcnews.go.com/US/wireStory/israel-ham...   
822  https://abcnews.go.com/International/wireStory...   
431  https://www.cnn.com/2023/10/13/media/israel-ha...   
573  https://abcnews.go.com/US/wireStory/israelis-a...   
538  https://www.cnn.com/2023/10/04/middleeast/jeru...   

                                                 title  \
461  5 things to know for Oct. 12: Israel, Economy,...   
561  What is Hamas? The group that rules the Gaza S...   
416  Who is El Deif, alleged mastermind of the Hama...   
743  War plunged Israel’s agricultural heartlands i...   
853  A contest erupts in Uganda over the tainted le...   
435  Investors flock to defensive stocks and safe h...   
709  Palestinians plead 'stop the bombs' at UN meet...   
700  The Israel-Hamas war could threaten already fr...   
822  Fights in bread lines, despair in shelters: Wa...   
431  Explosive claims about the Israel-Hamas war ar...   
573  Israelis abroad desperately try to head home t...   
538  Israeli police arrest five following uproar ov...   

                                                author  \
461                                                cnn   
561                     SARAH EL DEEB Associated Press   
416                                                cnn   
743   JULIA FRANKEL Associated Press and MOSHE EDRI...   
853                   RODNEY MUHUMUZA Associated Press   
435                                                cnn   
709                  EDITH M. LEDERER Associated Press   
700   FATIMA HUSSEIN Associated Press and JOSH BOAK...   
822                      ISABEL DEBRE Associated Press   
431                                                cnn   
573   JOCELYN NOVECK Associated Press, MENELAOS HAD...   
538                                                cnn   

                         date  \
461  2023-10-12T10:29:40.809Z   
561  2023-10-09T17:40:00.000Z   
416      2023-10-14T11:11:50Z   
743  2023-10-31T09:46:00.000Z   
853  2023-11-13T01:19:00.000Z   
435      2023-10-13T11:46:01Z   
709  2023-10-26T18:51:00.000Z   
700  2023-10-26T00:15:00.000Z   
822  2023-11-09T12:18:00.000Z   
431      2023-10-13T13:04:10Z   
573  2023-10-11T00:13:00.000Z   
538      2023-10-04T13:24:09Z   

                                               content  group  
461  CNN’s 5 Things brings you the news you need to...      0  
561          Hamas has ruled the Gaza Strip since 2007      1  
416  It is with a weird retrospective guilt that I ...      2  
743  The Israel-Hamas war has plunged Israel’s agri...      3  
853             Can Idi Amin possibly be rehabilitated      4  
435  The Israel-Hamas war is sending investors in s...      5  
709                   “Stop the bombs and save lives!”      6  
700  Economic crises are rippling through the count...      7  
822                Fistfights break out in bread lines      8  
431         The public is enveloped in the fog of war.      9  
573  Some Israelis living overseas aren’t running f...     10  
538  Israel Police arrested five people Wednesday o...     11

## Visualize data